### PR TITLE
Expand README.md

### LINKED ISSUE #94: Add a more substantial README for SQL schema experiment || S
Add:
- current scope
- how to develop: hasura-cli, .env template

### PR DESCRIPTION
**Pull request by haphut**
Fixes HSLdevcom/jore4#94

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @haphut)

___
*[.env.example, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12#-MW8KHUdEHd1RXwgs4_i:-MW8JNHd061XhAlygi2e:byuto6x) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/f2539d517753a18fa0561edf6531781929d65b15/.env.example#L2)):*
> ```Shell
> HASURA_GRAPHQL_ADMIN_SECRET=replace-me-1
> POSTGRES_PASSWORD=replace-me-2
> ```

Not sure if I'm understanding the logic here: if you are running postgres and hasura in docker-compose, it's pointless to protect the POSTGRES_PASSWORD and ADMIN_SECRET like this, it's anyway only gonna be used in the development setup. You could just have them hardcoded in the docker-compose file

If you however want to have the connection settings secret, because you might want your Hasura to connect to some remote db server, then you should have *all* secrets hidden in this `.env` file
___
*[README.md, line 13 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12#-MW8K73O5nL2A-D9yZOm:-MW8K73O5nL2A-D9yZOn:brsmm8) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/f2539d517753a18fa0561edf6531781929d65b15/README.md#L13)):*
> ```Markdown
> 1. Replace your own secrets into `.env`
> 1. Groan... to have `hasura/config.yml` in `hasura/` and to still use `.env` with Hasura CLI: `ln -s "$(pwd)/.env" hasura/.env`
> 1. Start the Hasura server with `docker-compose up`
> ```

Start the Hasura server *and Postgresql* with docker-compose up
___
*[README.md, line 17 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12#-MW8HejN5cqQVEgbziuW:-MW8HejN5cqQVEgbziuX:b-24sgq3) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/f2539d517753a18fa0561edf6531781929d65b15/README.md#L17)):*
> ```Markdown
> ### Change the SQL schema
> 
> While the local server is running, create a new migration with
> ```

while both hasura and the db server are running
___
*[README.md, line 31 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12#-MW8I4e58fGwP3akCv9G:-MW8I4e58fGwP3akCv9H:btodxba) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/f2539d517753a18fa0561edf6531781929d65b15/README.md#L31)):*
> ```Markdown
> cd hasura # To allow hasura-cli to find config.yaml
> hasura migrate status
> hasura migrate apply --up 1
> ```

does the migrate command have a version where it could take SENSIBLE_SNAKE_CASE_MIGRATION_NAME as parameter and apply all migrations until it is in? If yes, should rather use that to avoid confusions here you have an empty database and migrations 1, 2 and 3. If you only use --up 1, it will only drive migration no 1 while you might be actively working on migration 3
___
*[README.md, line 50 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12#-MW8Iy8OExR6WnYa1Ftt:-MW8Iy8OExR6WnYa1Ftu:b3x499x) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/f2539d517753a18fa0561edf6531781929d65b15/README.md#L50)):*
> ```Markdown
> ```
> 
> In the admin UI, navigate to the Data tab.
> ```

this probably wants to be a bulleted list? In this format, it will render as a continuous paragraph
___
*[README.md, line 58 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12#-MW8LQI99XfBN_jmEDur:-MW8LQI99XfBN_jmEDus:b-wmf3zz) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/f2539d517753a18fa0561edf6531781929d65b15/README.md#L58)):*
> ```Markdown
> When you are done clicking, commit the metadata changes into git.
> 
> #### Advice for permissions
> ```

it's a big plus that you also write advices like to the README

**Review by pallost — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12)* status: all files reviewed, 6 unresolved discussions (waiting on @haphut)

**Review by haphut — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @pallost)

___
*[.env.example, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12#-MW8KHUdEHd1RXwgs4_i:-MWNRULq1Ucpk0-Ueg4J:bnohqas) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/f2539d517753a18fa0561edf6531781929d65b15/.env.example#L2)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Not sure if I'm understanding the logic here: if you are running postgres and hasura in docker-compose, it's pointless to protect the POSTGRES_PASSWORD and ADMIN_SECRET like this, it's anyway only gonna be used in the development setup. You could just have them hardcoded in the docker-compose file

If you however want to have the connection settings secret, because you might want your Hasura to connect to some remote db server, then you should have *all* secrets hidden in this `.env` file
</blockquote></details>

I guess I considered those passwords the only secrets in local development. As Docker bypasses iptables and opens ports for the world, I'd rather not have hard coded passwords even for local development. Another option would be to open the ports for 127.0.0.1 only. I wonder if that could cause trouble in CI environments.
___
*[README.md, line 13 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12#-MW8K73O5nL2A-D9yZOm:-MWNTOKx53ZKyLHzzjYg:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/f2539d517753a18fa0561edf6531781929d65b15/README.md#L13)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Start the Hasura server *and Postgresql* with docker-compose up
</blockquote></details>

Done.
___
*[README.md, line 17 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12#-MW8HejN5cqQVEgbziuW:-MWNTOtY0G6bI2FCZ5yw:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/f2539d517753a18fa0561edf6531781929d65b15/README.md#L17)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

while both hasura and the db server are running
</blockquote></details>

Done.
___
*[README.md, line 31 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12#-MW8I4e58fGwP3akCv9G:-MWO2o6FCIdv_OBhzINo:bs3ldqv) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/f2539d517753a18fa0561edf6531781929d65b15/README.md#L31)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

does the migrate command have a version where it could take SENSIBLE_SNAKE_CASE_MIGRATION_NAME as parameter and apply all migrations until it is in? If yes, should rather use that to avoid confusions here you have an empty database and migrations 1, 2 and 3. If you only use --up 1, it will only drive migration no 1 while you might be actively working on migration 3
</blockquote></details>

Makes sense to change. Done.
___
*[README.md, line 50 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12#-MW8Iy8OExR6WnYa1Ftt:-MWO2pdu7TK3Jp0E__SN:bcvjgzp) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/f2539d517753a18fa0561edf6531781929d65b15/README.md#L50)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this probably wants to be a bulleted list? In this format, it will render as a continuous paragraph
</blockquote></details>

Good idea. Done.
___
*[README.md, line 58 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12#-MW8LQI99XfBN_jmEDur:-MWO2wGG80Zf82w0d_Wk:b-9755fn) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/f2539d517753a18fa0561edf6531781929d65b15/README.md#L58)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

it's a big plus that you also write advices like to the README
</blockquote></details>

Thank you!

**Review by pallost — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12#-:-MWTMju8034NzhTh09aF:bnfp4nl)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @haphut and @pallost)

___
*[.env.example, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12#-MW8KHUdEHd1RXwgs4_i:-MWTM8j38K6fi-3w3lvn:btlxy1w) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/f2539d517753a18fa0561edf6531781929d65b15/.env.example#L2)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

I guess I considered those passwords the only secrets in local development. As Docker bypasses iptables and opens ports for the world, I'd rather not have hard coded passwords even for local development. Another option would be to open the ports for 127.0.0.1 only. I wonder if that could cause trouble in CI environments.
</blockquote></details>

well, that is true, those port will be open... personally I use a router, so this is no issue for me :) well, leave it like this if you wish

**Review by lassemaatta — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12)* status: all files reviewed, 3 unresolved discussions (waiting on @haphut)

___
*[README.md, line 91 at r2](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12#-MWTQiip54h5LWlHUkL3:-MWTQiip54h5LWlHUkL4:b-hmshdw) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/29186ace2ece07b21a86610d0fa44606522ed785/README.md#L91)):*
> ```Markdown
> The name is not visible in the GraphQL API.
> 
> If the SQL schema generates a sensible default value for a column, e.g. for an ID column, do not allow inserts or updates for that column over the GraphQL API.
> ```

Surely this only applies to identifiers and not _all_ columns with default values?
___
*[README.md, line 94 at r2](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12#-MWTRRE56MNYyw2IHDrg:-MWTRRE56MNYyw2IHDrh:b8cxeh1) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/29186ace2ece07b21a86610d0fa44606522ed785/README.md#L94)):*
> ```Markdown
> 
> Do not allow inserting, updating or deleting data in reference tables ("enums") over the GraphQL API.
> Insert the values in a migration, instead.
> ```

One way to avoid this is to use proper [enums](https://www.postgresql.org/docs/11/datatype-enum.html), but I remember from somewhere that they come with their own drawbacks.

**Review by haphut — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12)* status: all files reviewed, 3 unresolved discussions (waiting on @lassemaatta and @pallost)

___
*[.env.example, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12#-MW8KHUdEHd1RXwgs4_i:-MWY0pUv9bvBbfOiWqbL:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/f2539d517753a18fa0561edf6531781929d65b15/.env.example#L2)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

well, that is true, those port will be open... personally I use a router, so this is no issue for me :) well, leave it like this if you wish
</blockquote></details>

Done.
___
*[README.md, line 91 at r2](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12#-MWTQiip54h5LWlHUkL3:-MWXxjfIDjbumOr3tTkU:b-u6ln3s) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/29186ace2ece07b21a86610d0fa44606522ed785/README.md#L91)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Surely this only applies to identifiers and not _all_ columns with default values?
</blockquote></details>

It applies to e.g. `created_at` timestamps, as well. Thanks, I'll try to clarify this bit.
___
*[README.md, line 94 at r2](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12#-MWTRRE56MNYyw2IHDrg:-MWXyW674UcMHYF51yG3:b-s5r9od) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/29186ace2ece07b21a86610d0fa44606522ed785/README.md#L94)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

One way to avoid this is to use proper [enums](https://www.postgresql.org/docs/11/datatype-enum.html), but I remember from somewhere that they come with their own drawbacks.
</blockquote></details>

Agreed. Enums are hard to change in migration files, as well. I'll try to clarify.

**Review by lassemaatta — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haphut)

**Review by lassemaatta — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haphut)

**Pull request closed without merging**
