### PR TITLE
Explicitly create extensions

### LINKED ISSUE #92: Explicitly create extensions in the SQL schema experiment || S
Currently `/docker-entrypoint-initdb.d/10_postgis.sh` within the Docker image `postgis/postgis` creates extensions into the public schema. Likely we need to handle extensions explicitly for the managed database in Azure.

One way to do it is to create one schema per extension:
```plpgsql
CREATE SCHEMA pgcrypto;
CREATE EXTENSION pgcrypto WITH SCHEMA pgcrypto;
```
And then to refer to them, e.g.:
```plpgsql
CREATE TABLE infrastructure_network.infrastructure_links (
  infrastructure_link_id uuid DEFAULT pgcrypto.gen_random_uuid() PRIMARY KEY,
  infrastructure_link_geog postgis.geography(LinestringZ,4326) NOT NULL,
  infrastructure_network_type text NOT NULL
    REFERENCES infrastructure_network.infrastructure_network_types
    (infrastructure_network_type);
);
```

### PR DESCRIPTION
**Pull request by tuokait**
!! Note: This change is not backwards compatible, but that should be
ok as currently this codebase is just for experiments.

Should resolve https://github.com/HSLdevcom/jore4/issues/92

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/14)

### CODE REVIEW

**Review by pallost — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/14)* status: all files reviewed, 2 unresolved discussions (waiting on @haphut and @tk-vincit)

___
*[hasura/migrations/1615200305272_init/up.sql, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/14#-MWTSoIm1qKTu1ujTNfv:-MWTSoIm1qKTu1ujTNfw:b-v48qw1) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6436f2d58f7f1cc1b07c55b4b359514f024a3fbd/hasura/migrations/1615200305272_init/up.sql#L5)):*
> ```TSQL
> CREATE SCHEMA pgcrypto;
> CREATE EXTENSION postgis WITH SCHEMA postgis;
> CREATE EXTENSION pgcrypto WITH SCHEMA pgcrypto;
> ```

what's the reason the extensions are using a dedicated schema namespace? Shouldn't these schemas be rather domain-specific instead of extension-specific?
___
*[hasura/migrations/1615200305272_init/up.sql, line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/14#-MWTT0K129HmpM3E2g_A:-MWTT0K129HmpM3E2g_B:b-tzof4p) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6436f2d58f7f1cc1b07c55b4b359514f024a3fbd/hasura/migrations/1615200305272_init/up.sql#L8)):*
> ```TSQL
> CREATE SCHEMA infrastructure_network;
> 
> SELECT set_config('search_path', 'postgis, pgcrypto,'||current_setting('search_path'), false);
> ```

what happens if the search_path already contains `pgcrypto` and/or `postgris` from a previous run?

**Review by lassemaatta — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/14)* status: all files reviewed, 2 unresolved discussions (waiting on @haphut and @pallost)

___
*[hasura/migrations/1615200305272_init/up.sql, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/14#-MWTSoIm1qKTu1ujTNfv:-MWTVA-A7smPrkVROOs-:b-6fb19q) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6436f2d58f7f1cc1b07c55b4b359514f024a3fbd/hasura/migrations/1615200305272_init/up.sql#L5)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

what's the reason the extensions are using a dedicated schema namespace? Shouldn't these schemas be rather domain-specific instead of extension-specific?
</blockquote></details>

I believe the original idea was that this would make it easier to find the extensions, especially if the functions are always referred through the schema (`pgcrypto.some_function()`). I originally had problems with the migrations, because they referred directly to `pgcrypto` functions, but the extension was not found in any of the schemas in the default search path.
___
*[hasura/migrations/1615200305272_init/up.sql, line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/14#-MWTT0K129HmpM3E2g_A:-MWTVpCZ-bRNcFPqM7ri:b-7ayktu) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6436f2d58f7f1cc1b07c55b4b359514f024a3fbd/hasura/migrations/1615200305272_init/up.sql#L8)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

what happens if the search_path already contains `pgcrypto` and/or `postgris` from a previous run?
</blockquote></details>

I'm not sure if it's a good idea to modify the search path here. I've always thought that it's the clients job to choose its own search path.

**Review by tuokait — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/14)* status: all files reviewed, 2 unresolved discussions (waiting on @haphut and @pallost)

___
*[hasura/migrations/1615200305272_init/up.sql, line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/14#-MWTT0K129HmpM3E2g_A:-MWTgVdO670SO6U09HF7:biu5yo5) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6436f2d58f7f1cc1b07c55b4b359514f024a3fbd/hasura/migrations/1615200305272_init/up.sql#L8)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

I'm not sure if it's a good idea to modify the search path here. I've always thought that it's the clients job to choose its own search path.
</blockquote></details>

Maybe @haphut has insight about this.

If we won't modify search path, then we have to explicitly mention used schemas in all migrations, e.g. `gen_random_uuid()`->`pgcrypto,gen_random_uuid()`

**Review by haphut — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/14)* status: all files reviewed, 2 unresolved discussions (waiting on @pallost)

___
*[hasura/migrations/1615200305272_init/up.sql, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/14#-MWTSoIm1qKTu1ujTNfv:-MWz5V_jBnyOJPWGmKmZ:barirqz) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6436f2d58f7f1cc1b07c55b4b359514f024a3fbd/hasura/migrations/1615200305272_init/up.sql#L5)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

I believe the original idea was that this would make it easier to find the extensions, especially if the functions are always referred through the schema (`pgcrypto.some_function()`). I originally had problems with the migrations, because they referred directly to `pgcrypto` functions, but the extension was not found in any of the schemas in the default search path.
</blockquote></details>

Yes, the extensions are used widely so we can use them from different domain schemas without adding them everywhere.
___
*[hasura/migrations/1615200305272_init/up.sql, line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/14#-MWTT0K129HmpM3E2g_A:-MWz5nIy4CxCHElxowtB:bdb7d7j) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6436f2d58f7f1cc1b07c55b4b359514f024a3fbd/hasura/migrations/1615200305272_init/up.sql#L8)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Maybe @haphut has insight about this.

If we won't modify search path, then we have to explicitly mention used schemas in all migrations, e.g. `gen_random_uuid()`->`pgcrypto,gen_random_uuid()`
</blockquote></details>

`set_config` only affects the current session.

Hasura needs pgcrypto: https://hasura.io/docs/latest/graphql/core/deployment/postgres-requirements.html#pgcrypto-in-pg-search-path .

If we drop `public` like I suggested, we'd need to put at least `pgcrypto`, and probably `postgis`, into Hasura's `search_path`. I'm okay with the `ALTER DATABASE` solution described in the linked page. Maybe add something like this above and maybe remove the `set_config` line (I did not try this yet):
```plpgsql
DO $$
BEGIN
   EXECUTE 'ALTER DATABASE '||current_database()||' SET search_path = postgis, pgcrypto';
END
$$;
```

Alternatively we let Hasura use `public` and look the other way.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/14)* status: all files reviewed, 2 unresolved discussions (waiting on @haphut and @pallost)

___
*[hasura/migrations/1615200305272_init/up.sql, line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/14#-MWTT0K129HmpM3E2g_A:-MX1SjII6aiYXpGihzN5:b-g17i8x) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6436f2d58f7f1cc1b07c55b4b359514f024a3fbd/hasura/migrations/1615200305272_init/up.sql#L8)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

`set_config` only affects the current session.

Hasura needs pgcrypto: https://hasura.io/docs/latest/graphql/core/deployment/postgres-requirements.html#pgcrypto-in-pg-search-path .

If we drop `public` like I suggested, we'd need to put at least `pgcrypto`, and probably `postgis`, into Hasura's `search_path`. I'm okay with the `ALTER DATABASE` solution described in the linked page. Maybe add something like this above and maybe remove the `set_config` line (I did not try this yet):
```plpgsql
DO $$
BEGIN
   EXECUTE 'ALTER DATABASE '||current_database()||' SET search_path = postgis, pgcrypto';
END
$$;
```

Alternatively we let Hasura use `public` and look the other way.
</blockquote></details>

these observations are good to document at least as a comment to the above migration ^

**Review by haphut — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/14)* status: all files reviewed, 2 unresolved discussions (waiting on @pallost)

___
*[hasura/migrations/1615200305272_init/up.sql, line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/14#-MWTT0K129HmpM3E2g_A:-MX0LdNl5SkrhSKlXrrL:bgo624c) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/6436f2d58f7f1cc1b07c55b4b359514f024a3fbd/hasura/migrations/1615200305272_init/up.sql#L8)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

these observations are good to document at least as a comment to the above migration ^
</blockquote></details>

Some missed details:

I believe the `set_config` for current session will be required after `ALTER DATABASE`. The `ALTER DATABASE` will likely not affect the current session. 

Above snippet has an indent of 3 by accident. I'd also add spaces around the operators.

`down.sql` might then need a similar snippet but with
```plpgsql
'ALTER DATABASE ' || current_database() || ' RESET search_path;'
```

I'm not sure if the result of `current_database()` is properly quoted or if in both uses it should be written with:
```plpgsql
quote_ident(current_database())
```

**Review by haphut — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/14)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @lassemaatta and @pallost)

**Pull request merged**
