### PR TITLE
Simplify infrastructure network types

### LINKED ISSUE #95: Simplify infrastructure_network_types in SQL schema experiment ||S
Simplify `infrastructure_network_types` to have only [one column](https://hasura.io/docs/latest/graphql/core/databases/postgres/schema/enums.html#using-foreign-key-references-to-a-single-column-table) as wisely suggested by @jarkkoka:
```postgresql
infrastructure_network_type text PRIMARY KEY
```
and update the metadata accordingly.

### PR DESCRIPTION
**Pull request by haphut**
Fixes HSLdevcom/jore4#95.

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/13)

### CODE REVIEW

**Review by haphut — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/13)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jarkkoka and @lassemaatta)

*[a discussion](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/13#-MW4ycwx4baMcSFb9LSM:-MW4ycwx4baMcSFb9LSN:bn13j25) (no related file):*
While we have the luxury to drop the data in the database at any given time, maybe it would be easier to just write one schema file. I find one `CREATE TABLE` easier to read than several `ALTER TABLE`s.

We totally should practice migrations before we are even close to production. I'd just like to separate the migration exercises and tests from developing the initial schema.

---

**Review by haphut — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/13)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @jarkkoka and @lassemaatta)

___
*[hasura/migrations/1615985978956_simplify_infrastructure_network_types/up.sql, line 38 at r2](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/13#-MW4zTf_8uCqOEfYBmqD:-MW4zTf_8uCqOEfYBmqE:b-p9n9bt) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/a38aa7e2b151ed76b904aafa4dcedd0760a6b2fa/hasura/migrations/1615985978956_simplify_infrastructure_network_types/up.sql#L38)):*
> ```TSQL
>   ('tram_track'),
>   ('metro_track'),
>   ('waterway');
> ```

@ossiberg I tried finding the most accurate jargon for these. Perhaps you can help. The idea is to model the steel tracks, asphalt and so on, not vehicle modes per se. I found e.g. "right of way" and "support" but neither seemed to provide the right taxonomy.

The purpose of these is to allow us to restrict which infrastructure network we show in different contexts of the UI. E.g. when planning tram routes, the road network is maybe not relevant.

Transmodel has toy concepts "road", "railway" and "wire" and tells the reader to look up other standards. Here sticking to Transmodel would not allow us to serve ferry planning at all or to separate metro from train or trolley busses from trams (which may be relevant elsewhere).

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/13)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @haphut and @lassemaatta)

___
*[hasura/migrations/1615985978956_simplify_infrastructure_network_types/down.sql, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/13#-MW5iRrr7UR_O7h_xK39:-MW5iRrsBCilxLAxay4G:byg62gv) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/d0abd30535c52600db98835f0c2a3415faee97f1/hasura/migrations/1615985978956_simplify_infrastructure_network_types/down.sql#L2)):*
> ```TSQL
> ALTER TABLE infrastructure_network.infrastructure_links
>   DROP COLUMN infrastructure_network_type RESTRICT;
> ```

Huolellisesti mietitty, kun olet käyttänyt RESTRICT-avainsanaa :+1:

**Review by haphut — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/13)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @jarkkoka and @lassemaatta)

___
*[hasura/migrations/1615985978956_simplify_infrastructure_network_types/down.sql, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/13#-MW5iRrr7UR_O7h_xK39:-MWOUcc-9t0TyfgQg5ui:b-ucfknh) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/d0abd30535c52600db98835f0c2a3415faee97f1/hasura/migrations/1615985978956_simplify_infrastructure_network_types/down.sql#L2)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Huolellisesti mietitty, kun olet käyttänyt RESTRICT-avainsanaa :+1: 
</blockquote></details>

Thanks!

**Review by haphut — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/13)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @jarkkoka and @lassemaatta)

___
*[hasura/migrations/1615985978956_simplify_infrastructure_network_types/down.sql, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/13#-MW5iRrr7UR_O7h_xK39:-MWbtPcL4O5Uk9lz4Eb4:btuan60) ([raw file](https://github.com/hsldevcom/jore4-sql-schema-experiment/blob/d0abd30535c52600db98835f0c2a3415faee97f1/hasura/migrations/1615985978956_simplify_infrastructure_network_types/down.sql#L2)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Thanks!
</blockquote></details>

Apparently Reviewable requires you to accept the PR. The little dot attached to your avatar opens up a menu where you can choose what type of a comment you send. Based on the comment text I assume it was an approval but Reviewable by default chose to request changes.

**Review by jarkkoka — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-sql-schema-experiment/13)* status: all files reviewed, 3 unresolved discussions (waiting on @jarkkoka and @lassemaatta)

**Pull request merged**
